version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: openmonitor-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: openmonitor
      MYSQL_USER: openmonitor
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups:/backups
    # ports:
      # - "3306:3306"
    networks:
      - openmonitor-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  valkey:
    image: valkey/valkey:8.1.3-alpine
    container_name: openmonitor-valkey
    restart: unless-stopped
    volumes:
      - ./conf/valkey.conf:/etc/valkey/valkey.conf
    networks:
      - openmonitor-network
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5

  bot:
    build: .
    container_name: openmonitor-bot
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - DATABASE_URL=mysql://openmonitor:${MYSQL_PASSWORD}@mysql:3306/openmonitor
      - OWNER_ID=${OWNER_ID}
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - VALKEY_HOSTS=${VALKEY_HOSTS}
      - VALKEY_USE_TLS=${VALKEY_USE_TLS}
      - VALKEY_KEY_EXPIRY_SECONDS=${VALKEY_KEY_EXPIRY_SECONDS}
    volumes:
      - ./logs:/app/logs
    networks:
      - openmonitor-network

volumes:
  mysql_data:
    driver: local

networks:
  openmonitor-network:
    driver: bridge